name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - amrvac3.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install graphviz
      - uses: DenverCoder1/doxygen-github-pages-action@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: docs/html
          config_file: doc/Doxyfile
